# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_metadata.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15update_metadata.proto\x12\x16chromeos_update_engine"1\n\x06Ext'
    b'ent\x12\x13\n\x0bstart_block\x18\x01 \x01(\x04\x12\x12\n\nnum_blocks'
    b'\x18\x02 \x01(\x04"\xeb\x03\n\x10InstallOperation\x12;\n\x04type\x18'
    b'\x01 \x02(\x0e2-.chromeos_update_engine.InstallOperation.Type\x12'
    b'\x13\n\x0bdata_offset\x18\x02 \x01(\x04\x12\x13\n\x0bdata_length\x18'
    b'\x03 \x01(\x04\x123\n\x0bsrc_extents\x18\x04 \x03(\x0b2\x1e.chromeos'
    b'_update_engine.Extent\x12\x12\n\nsrc_length\x18\x05 \x01(\x04\x123\n'
    b'\x0bdst_extents\x18\x06 \x03(\x0b2\x1e.chromeos_update_engine.Extent'
    b'\x12\x12\n\ndst_length\x18\x07 \x01(\x04"\xdd\x01\n\x04Type\x12\x0b'
    b'\n\x07REPLACE\x10\x00\x12\x0e\n\nREPLACE_BZ\x10\x01\x12\x08\n\x04MOV'
    b'E\x10\x02\x12\n\n\x06BSDIFF\x10\x03\x12\x0f\n\x0bSOURCE_COPY\x10\x04'
    b'\x12\x11\n\rSOURCE_BSDIFF\x10\x05\x12\x08\n\x04ZERO\x10\x06\x12\x0b'
    b'\n\x07DISCARD\x10\x07\x12\x0e\n\nREPLACE_XZ\x10\x08\x12\x0c\n\x08PUF'
    b'FDIFF\x10\t\x12\x11\n\rBROTLI_BSDIFF\x10\n\x12\x0c\n\x08ZUCCHINI\x10'
    b'\x0b\x12\x12\n\x0eLZ4DIFF_BSDIFF\x10\x0c\x12\x14\n\x10LZ4DIFF_PUFFDI'
    b'FF\x10\r"+\n\rPartitionInfo\x12\x0c\n\x04size\x18\x01 \x01(\x04\x12'
    b'\x0c\n\x04hash\x18\x02 \x01(\x0c"\xed\x01\n\x0fPartitionUpdate\x12'
    b'\x16\n\x0epartition_name\x18\x01 \x02(\t\x12A\n\x12old_partition_inf'
    b'o\x18\x06 \x01(\x0b2%.chromeos_update_engine.PartitionInfo\x12A\n'
    b'\x12new_partition_info\x18\x07 \x01(\x0b2%.chromeos_update_engine.Pa'
    b'rtitionInfo\x12<\n\noperations\x18\x08 \x03(\x0b2(.chromeos_update_e'
    b'ngine.InstallOperation"\x87\x01\n\x14DeltaArchiveManifest\x12\x18\n'
    b'\nblock_size\x18\x03 \x01(\r:\x044096\x12\x18\n\rminor_version\x18'
    b"\x0c \x01(\r:\x010\x12;\n\npartitions\x18\r \x03(\x0b2'.chromeos_upd"
    b'ate_engine.PartitionUpdate'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "update_metadata_pb2", globals()
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    _EXTENT._serialized_start = 49
    _EXTENT._serialized_end = 98
    _INSTALLOPERATION._serialized_start = 101
    _INSTALLOPERATION._serialized_end = 592
    _INSTALLOPERATION_TYPE._serialized_start = 371
    _INSTALLOPERATION_TYPE._serialized_end = 592
    _PARTITIONINFO._serialized_start = 594
    _PARTITIONINFO._serialized_end = 637
    _PARTITIONUPDATE._serialized_start = 640
    _PARTITIONUPDATE._serialized_end = 877
    _DELTAARCHIVEMANIFEST._serialized_start = 880
    _DELTAARCHIVEMANIFEST._serialized_end = 1015
# @@protoc_insertion_point(module_scope)
